#!/bin/bash

in="../user/settings.ini"
out="../autoexec/generated/global_vars_user.ahk"

mkdir -p "$(dirname "$out")"

echo -e "; *** this file is generated by install.sh *** \n\n" > "$out"

dur_sep=100
max_dur_level=2

var=$(sed -nr 's/.*duration_level_separation_milliseconds: *([1-9][0-9]+).*/\1/p' "$in")
if ! [ "$var" = "" ]; then
	dur_sep=$var
fi
echo "duration_level_separation_milliseconds := $dur_sep" >> "$out"

var=$(sed -nr 's/.*gesture_max_duration_level: *([0-9]).*/\1/p' "$in")
if ! [ "$var" = "" ]; then
	max_dur_level=$var
fi
echo "gesture_max_duration_level := $max_dur_level" >> "$out"
